version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=wiliams
      - POSTGRES_PASSWORD=administrador
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=administrador@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8001:80
